import type { NextPage } from 'next';
import Head from 'next/head';

const Checkout: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Checkout</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h2 className="text-2xl font-extrabold tracking-tight text-gray-900">
				Checkout
			</h2>
		</div>
	);
};

export default Checkout;
