import { useEffect } from 'react';
import Head from 'next/head';
import Item from '../components/Item';
import { Product } from '../interfaces';
import useSWR from 'swr';
import { useSession, signIn } from 'next-auth/react';

const Favorite = () => {
	const { data: session } = useSession();

	useEffect(() => {
		!session && signIn();
	}, []);

	const fetcher = async (url) => {
		const { accessToken } = session;
		console.log(accessToken);

		const response = await fetch(url, {
			headers: {
				Authorization: `Bearer ${accessToken}`,
			},
		});
		const data: Product[] = await response.json();

		return data;
	};

	const { data: favorites, error } = useSWR(
		`http://localhost:5000/api/favorites`,
		fetcher
	);
	if (error) return <div>An error has occurred</div>;
	if (!favorites) return <div>Loading...</div>;

	return (
		session && (
			<div>
				<Head>
					<title>Favorites</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<h2 className="text-2xl font-extrabold tracking-tight text-gray-900">
					Favorites
				</h2>
				{favorites.map((favorite) => (
					<Item key={favorite.product_id} product={favorite} />
				))}
			</div>
		)
	);
};

export default Favorite;
