import type { NextPage, GetStaticProps, InferGetStaticPropsType } from 'next';
import Head from 'next/head';
import Products from '../components/Products';
import { Product } from '../interfaces';

const Home: NextPage = ({
	products,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Products products={products} />
		</div>
	);
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
	const res = await fetch(`${process.env.BASE_URL}/api/products`);
	const products: Product[] = await res.json();
	return {
		props: {
			products,
		},
	};
};
