import type { GetStaticProps } from 'next';
import Head from 'next/head';
import Products from '../components/Products';
import { Product } from '../interfaces';

interface Props {
	products: Product[];
}

const Offers = ({ products }: Props) => {
	return (
		<div>
			<Head>
				<title>Offers</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Products products={products} title="Offers" />
		</div>
	);
};

export default Offers;

export const getStaticProps: GetStaticProps = async () => {
	const res = await fetch(`${process.env.BASE_URL}/api/products`);
	const products: Product[] = await res.json();
	return {
		props: {
			products,
		},
	};
};
