import type { GetStaticProps } from 'next';
import Head from 'next/head';
import Item from '../components/Item';
import { Product, Error } from '../interfaces';
import { withPageAuthRequired } from '@auth0/nextjs-auth0';

interface Props {
	orders: Product[];
	error?: Error;
	user: any;
}

const Order = ({ orders }: Props) => {
	return (
		<div>
			<Head>
				<title>Favorites</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h2 className="text-2xl font-extrabold tracking-tight text-gray-900">
				Orders
			</h2>
			{orders.map((order) => (
				<Item key={order.product_id} product={order} />
			))}
		</div>
	);
};

export default withPageAuthRequired(Order);

export const getStaticProps: GetStaticProps = async () => {
	const res = await fetch(`${process.env.BASE_URL}/api/orders`);

	if (res.status !== 200) {
		const error = await res.json();

		return {
			props: {
				orders: [],
				error: error,
			},
		};
	}
	const orders: Product[] = await res.json();

	return {
		props: {
			orders,
		},
	};
};
