import Head from 'next/head';
import { useEffect } from 'react';

import { useSession, signIn } from 'next-auth/react';

const Profile = () => {
	const { data: session } = useSession();
	useEffect(() => {
		!session && signIn();
	}, []);

	return (
		session && (
			<div>
				<Head>
					<title>Profile</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<h2 className="text-2xl font-extrabold tracking-tight text-gray-900">
					Profile
				</h2>
				<div>
					<img src={session.user.name} alt={session.user.name} />
					<h2>{session.user.name}</h2>
					<p>{session.user.email}</p>
				</div>
			</div>
		)
	);
};

export default Profile;
